#pragma once
#include "../../NovusTypes.h"

enum class Opcode : u16
{
    INVALID,
    CMSG_LOGON_CHALLENGE,
    SMSG_LOGON_CHALLENGE,
    CMSG_LOGON_HANDSHAKE,
    SMSG_LOGON_HANDSHAKE,
    CMSG_CONNECTED,
    SMSG_CONNECTED,
    MSG_REQUEST_ADDRESS,
    SMSG_SEND_ADDRESS,
    MSG_REQUEST_INTERNAL_SERVER_INFO,
    SMSG_SEND_FULL_INTERNAL_SERVER_INFO,
    SMSG_SEND_ADD_INTERNAL_SERVER_INFO,
    SMSG_SEND_REMOVE_INTERNAL_SERVER_INFO,
    CMSG_REQUEST_REALMLIST,
    SMSG_SEND_REALMLIST,
    CMSG_SELECT_REALM,
    SMSG_CREATE_PLAYER,
    SMSG_CREATE_ENTITY,
    SMSG_DELETE_ENTITY,
    SMSG_UPDATE_ENTITY,
    MSG_MOVE_ENTITY,
    MSG_MOVE_HEARTBEAT_ENTITY,
    MSG_MOVE_STOP_ENTITY,
    MAX_COUNT
};