#pragma once
#include "../../NovusTypes.h"

enum class Opcode : u16
{
    INVALID,
    CMSG_LOGON_CHALLENGE,
    SMSG_LOGON_CHALLENGE,
    CMSG_LOGON_RESPONSE,
    SMSG_LOGON_RESPONSE,
    CMSG_CONNECTED,
    SMSG_CREATE_PLAYER,
    SMSG_CREATE_ENTITY,
    SMSG_DELETE_ENTITY,
    SMSG_UPDATE_ENTITY,
    MSG_MOVE_ENTITY,
    MSG_MOVE_HEARTBEAT_ENTITY,
    MSG_MOVE_STOP_ENTITY,
    IMSG_HANDSHAKE,
    IMSG_HANDSHAKE_RESPONSE,
    MAX_COUNT
};